@startuml

package interaction {

    +interface Interactive{
        --
            + {method} {static} interactWithOutput (Interactive)
            + {method} default interactWithOutput ()
            + {method} default interact (ButtonDetails)

    }

    +class ButtonDetails {
            + {field} type : Type
            + {field} symbol : char
        --
        ..get/set..
    }

    +enum Interaction implements Interactive{
            BRACKET_IN,
            BRACKET_OUT,
            ADD_TO_PARSER,
            SWITCH_SIGN,
            ADD_TO_QUEUE,
            SOLVE,
            UNDO,
            CLEAR,
            RESET,
            EMPTY
        ..
    }

'    Interactive ..left..* ButtonDetails
    Interactive *..right..> ButtonDetails
}


() Parsable
() Node
() MainPanel
() Type

'Interactive ..left.* MainPanel
Interactive *..right.> MainPanel

'Interaction .down.* MainPanel
Interaction *.up.> MainPanel

'Interaction ..up* Node
Interaction *..down> Node

'Interaction ..up* Parsable
Interaction *..down> Parsable

'ButtonDetails -left-o Type
ButtonDetails o-right-> Type

@enduml