@startuml

package _temp.calculation{

/'    +abstract Treebeard{
            ~ {field} {static} Node leftSlot
            ~ {field} {static} Node rootSlot
            ~ {field} {static} Node riteSlot
        ..
            ~ {field} {static} bool leftNull
            ~ {field} {static} bool rootNull
            ~ {field} {static} bool riteNull
        __
            ~ {method} {static} int identifySlot ()
    }'/

    +abstract Node{
            ~   {static} Node mainRoot
        ..
            ~   {field} Node localRoot
            ~   {field} Node localLeft
            ~   {field} Node localRite
        ..
            ~   {field} dbl value = NaN
            ~   {field} NodeType type
        __
                {method} ... getter/setter
'            +   {method} setValue ()
'            ~   {method} setValue (value)
        ..
            +   {method} void resetType ()
            +   {method} calculate (dbl , dbl )
            ~   {method} valueIsNaN ()
    }

    +class Value{
            ~   {static} final NodeType classType = VAL
            __
            +   {method} @Ovr void setType ()
    }

    ~abstract Calculation{
    }

    package calculations <<Rectangle>> {
        class Calculation_?{
                ~ {field} {static} NodeType classType
            __
                + {method} @Ovr void setType ()
                + {method} @Ovr calculate ()
        }
    }

    ~enum NodeType{
        BRACKET_IN_OUT
        EXP_ROOT
        MULTI_DIV
        ADD_SUB
        VAL
    }
}

    Node            o.     Node
    Node            <|-    Value           : ext
    Node            <|--    Calculation     : ext
    Calculation     <--     calculations    : ext
    Calculation     *.     Value
    Calculation     .|>    NodeType
    Value           ..|>    NodeType

@enduml