@startuml


package GUI {

    component output
    component input
}

package logic {
    component Parsable
    component Solvable
}

package data {
    component Queueable
    component Treeable
    component node
}

package interaction{
component Interactive
}

[input]     -up-o    [Interactive]

[Interactive] -up-o     [Parsable]
[Interactive] -right-o   [node]
[Solvable]  <|-down-    [node]

[output]    *-right-       [input]
[output]    -up-o    [node]

[Queueable] <|-left- [Treeable]

[node]  -right-|>    [Treeable]

@enduml