@startuml

package GUI {
    component output
    component input
}

package logic {
    component Parsable
    component Solvable

}

package data {
    component memory
    component Queueable
    component Treeable
    component Nodeable
}

[input]     -right-o    logic
logic       <|-down-    [Nodeable]
[output]    *-up--      [input]
[output]    -right-o    [memory]

[Queueable] *-down-     [memory]

[Nodeable]  -left-|>    [Queueable]
[Nodeable]  -down-|>    [Treeable]

@enduml