@startuml

package GUI {
    component output
    component input
}

package logic {

    component Solvable

}

package data {
'    component memory
    component Queueable
    component Treeable
    component node
}

component Parsable

[input]     -right-o    [Parsable]
[Parsable] -down-* [node]
logic       <|-down-    [node]
[output]    *-up-      [input]
[output]    -right-o    [node]


[Queueable] <|-left- [Treeable]

[node]  -right-|>    [Treeable]

@enduml