@startuml

package data {

    +interface data.Queueable {

    }

    +interface Treeable extends data.Queueable{

    }

    +interface data.Nodeable extends Treeable{

    }

    +class data.Queue2 {

    }

    +class data.Node {

    }

    data.Queue2       -right-*    data.Queueable
    data.Node        -right-*    data.Nodeable
}

    () Solvable
    () Parsable

    data.Queue2       -right-|>   Solvable
    data.Node        -right-|>   Parsable
    data.Queue2       ---*     data.Node

@enduml