@startuml

    () Solvable
    () Parsable

package data {

    +interface Queueable {
    }

    +interface Treeable {
    }

    +class Node {
    }
}

        Queueable   *..     Queueable
        Treeable    .*     Queueable
        Treeable    <|--   Node
        Queueable   <|--    Node
        Parsable    <|-    Node
        Node        -left-|>  Solvable

@enduml