@startuml

interface AlgebraicOperational
interface CharIdentification
class AlgebraicOperation
class Number
class OperationCache

AlgebraicOperational <.. AlgebraicOperation
AlgebraicOperational o-- Number : static
CharIdentification  o..o OperationCache
AlgebraicOperational o.. CharIdentification

OperationCache o-- Number

/'
class ArrayList {
Object[] elementData
size()
}'/

@enduml