@startuml
package input {

    +interface Enqueued{
        __

    }

    ~class Queuer{
    }

    +interface Queueable{
        __

    }

    ~abstract class QueueCore{
            ~{field} Queueable head
            ~{field} Queueable tail
    }

    ~interface Queuing{
        __
            ~{method} void extendQueue(Queuing, Enqueued)
            ~{method} void increaseCounters
            ~{method} void decreaseCounters
    }

    ~class Queue{
            ~{field} int[] priorityCounter
            ~{field} int counter
    }

    Enqueued <|-- Queuer : impl
    Queueable <|-- QueueCore :impl
    Queuing <|-- Queue :impl

    QueueCore <|-- Queuer : ext
    QueueCore <|-- Queue : ext
    Queue "2" *- Queuer
    Queuer "2" *- Queuer

}
@enduml