@startuml

rectangle Q0

rectangle Q1
rectangle Q2
rectangle Q3

rectangle QN

Q0 "next" <--right--> "prev" Q1

Q1  -up-() null1:head
Q1  -up-() null2:tail

Q1 "next" <--right--> "prev" Q2

Q2  -up-() null3:head
Q2  -up-() null4:tail

Q2 "next" <--right--> "prev" Q3

Q3  -up-() null5:head
Q3  -up-() null6:tail

Q3 "next" <--right--> "prev" QN


@enduml