@startuml

rectangle Q0

rectangle Q1
rectangle Q2
rectangle Q3

rectangle QN

Q1 -left-() null0:prev1

Q1  -up-() null1:"left"
Q1  -up-() null2:"rite"


Q0 "next0" <-right-> "prev2" Q2

Q1 "next1" -down->  Q2

Q2  --up-() null3:"left"

Q2 "rite2" <-up-> "prev3" Q3

Q2 "next2" <-right-> "prevN" QN

Q3  -up-() null5:"left"
Q3  -up-() null6:"rite"

Q3  -right-() nullN:next3

Q1 -[hidden]- Q0
Q3 -[hidden]- QN


@enduml