@startuml
package calculation {

    +interface Nodeable {
            + {method} Nodeable getLocalLeft()
            + {method} Nodeable getLocalRoot()
            + {method} Nodeable getLocalRite()
            + {method} Typical getType()
            + {method} Double getValue()
        ..
            + {method} void setLocalLeft (Nodeable)
            + {method} void setLocalRoot (Nodeable)
            + {method} void setLocalRite (Nodeable)
            + {method} void setType (Typical)
            + {method} void setValue (Double)
            + {method} void setValue ()
    }

    +class Node {
            ~ {field} Nodeable LocalLeft
            ~ {field} Nodeable LocalRoot
            ~ {field} Nodeable LocalRite
            ~ {field} Typical type
            ~ {field} Double value
        --
            # {method} Double calculate ( Nodeable, Nodeable)
        ..@Override..
            +{method}/.../
    }

    +class Value {
        ..@Override..
    }

    +abstract class Calculation {
        ..abstract..
            #{method} double perform (double, double)    
        ..@Override..
            #{method} calculate
    }

    package calculations <<Rectangle>> {
        class Calculation_? {
            ..@Override..
                #{method} perform
        }
    }

    +interface Typical{
        ..default..
            +{method} Typical valueOf(Typical)
        ..
            ~{method} Nodeable interact()
   }

    +enum NodeType{
        ..@Override..
             {interact()} BRACKET_IN
             {interact()} BRACKET_OUT
             {interact()} EXPONENT
             {interact()} ROOT
             {interact()} MULTIPLY
             {interact()} DIVIDE
             {interact()} ADD
             {interact()} SUBTRACT
             {interact()} VALUE
             {interact()} SPIN
             {interact()} EVALUATE
             {interact()} CLEAR
             {interact()} UNDO
   }

    Nodeable <|-- Node
    Node <|-- Calculation : ext
    Typical <|- NodeType : ext
    Nodeable <|- Typical

    Node <|- Value : ext
    Calculation <|- calculations    : ext
}
@enduml