@startuml

package  "move que3 root" <<Rectangle>>{

    object que1{
        ~ Double value
    }
        null ()- "left" que1
        que1 "rite" -() null

    object que2{
        ~ Double value = NaN
        ~ type
    }
        que1 "root" *--* "left" que2
        que3 "root" *--* "rite" que2
        que2 "root" --() null

    object que3{
        ~ Double value
    }
        null ()- que3
        que3 -() null

}

     head ()-- que2
     que2 --() tail

@enduml