@startuml

+interface Legs{
    ..
    {method} A
}
-interface Left{
    ..
    {method} B
}
+class LeftLegs{
    ..@Override..
        {method} B
}

-interface Rite{
    ..
    {method} C
}
+class RiteLegs{
    ..@Override..
        {method} C
}
-class Feet{
    ..
    {method} A
}

    Left    -|>     Legs   :   ext
    Legs   <|-     Rite     :   ext

    Feet   <|-     RiteLegs   :   ext
    LeftLegs      -|>     Feet   :   ext

    Left    <|--    LeftLegs      :   impl
    Rite     <|--    RiteLegs   :   impl

@enduml